---
python_app_repo: https://github.com/comp523-jarvis/timetracker-web

python_app_name: ulimi-timetracker
python_app_package: timetracker

django_venv: "{{ python_app_venv }}"
django_app_root: "{{ python_app_project_root }}/{{ python_app_package }}"

django_admin_env:
  ADMIN_PASSWORD: "{{ admin_password }}"
  ADMIN_USERNAME: admin

django_env:
  DJANGO_ALLOWED_HOSTS: "{{ domain_name }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"

  DJANGO_DEFAULT_FROM_EMAIL: chathan@driehuys.com
  DJANGO_SES_ENABLED: true

  DJANGO_DB_HOST: "{{ db_host }}"
  DJANGO_DB_NAME: "{{ db_name }}"
  DJANGO_DB_PASSWORD: "{{ db_password }}"
  DJANGO_DB_PORT: "{{ db_port }}"
  DJANGO_DB_USER: "{{ db_user }}"

  DJANGO_DIALOGFLOW_INTENT_CLOCK_IN: 'projects/alpha-44257/agent/intents/8c12b7c5-87d7-4b4f-a66e-e8bfbd115405'
  DJANGO_DIALOGFLOW_INTENT_CLOCK_OUT: 'projects/alpha-44257/agent/intents/8c82a2e0-a7ad-42a1-aac0-fc5557640e20'

app_config_directory: /etc/ulimi-timetracker
app_config_env_vars: "{{ django_base_env | combine(django_env) }}"

gunicorn_env_file: "{{ app_config_env_file }}"
gunicorn_venv: "{{ python_app_venv }}"
gunicorn_working_dir: "{{ django_app_root }}"
gunicorn_wsgi_app: "{{ python_app_package }}.wsgi:application"

letsencrypt_domain: "{{ domain_name }}"
letsencrypt_email: "chathan@driehuys.com"

nginx_proxy_socket: "{{ gunicorn_socket_uri }}"
nginx_server_name: "{{ domain_name }}"
