---
python_app_repo: https://github.com/comp523-jarvis/timetracker-web

python_app_name: ulimi-timetracker
python_app_package: timetracker

postgres_db_password: "{{ db_password }}"

django_venv: "{{ python_app_venv }}"
django_app_root: "{{ python_app_project_root }}/{{ python_app_package }}"

django_env:
  DJANGO_ALLOWED_HOSTS: "{{ domain_name }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"

  DJANGO_DB_HOST: localhost
  DJANGO_DB_NAME: "{{ postgres_db_name }}"
  DJANGO_DB_PASSWORD: "{{ db_password }}"
  DJANGO_DB_PORT: "5432"
  DJANGO_DB_USER: "{{ postgres_db_user }}"

gunicorn_venv: "{{ python_app_venv }}"
gunicorn_working_dir: "{{ django_app_root }}"
gunicorn_wsgi_app: "{{ python_app_package }}.wsgi:application"

letsencrypt_domain: "{{ domain_name }}"
letsencrypt_email: "chathan@driehuys.com"

nginx_proxy_socket: "{{ gunicorn_socket_uri }}"
nginx_server_name: "{{ domain_name }}"
