---
- name: Install Postgres
  become: true
  apt:
    name:
      - libpq-dev
      - postgresql
      - postgresql-contrib
      - python-psycopg2

- name: Create database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ postgres_db_name }}"

- name: Create database user
  become: true
  become_user: postgres
  postgresql_user:
    db: "{{ postgres_db_name }}"
    name: "{{ postgres_db_user }}"
    password: "{{ postgres_db_password }}"
    priv: ALL
